routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\CasemangeController;
use App\Http\Controllers\CaseitemController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
// Route::get('/', function () { return view('home');});
Route::resource('/', HomeController::class);
Route::resource('/lead', LeadController::class);
Route::resource('/cases', CasemangeController::class);
Route::resource('/item', CaseitemController::class);
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/lead.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class lead extends Model
{
    use HasFactory;
	protected $fillable = [
        'name', 'phone', 'email','remark','statusid','url','avatar'
    ];

    public function leadStatus()
	{
		return $this->belongsTo(lead_status::class, 'statusid');
	}

    public function cases()
	{
		return $this->hasMany(casemange::class);
	}
}

app/Http/Controllers/LeadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Lead;
use App\Models\lead_status;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class LeadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    { 
        
        $alllead= Lead::count();
        
        $leadstatus=lead_status::all();
		$data = Lead::with('leadStatus',)->withCount('cases')->orderByDesc('updated_at')->orderByDesc('created_at');
        
		if ($request->has('search')) {
			
			$data = $data->where('name', 'like', "%{$request->search}%")
						   ->orWhere('email', 'like', "%$request->search%")
                           ->orWhere('phone', 'like', "%$request->search%")
						   ->paginate(10)
						   ->withQueryString();
			
			
		}else{
			$data = $data->paginate(10);
		}   
        
        
        $progress=($data->total()/$alllead)*100;
        
		
        
        return view('lead.index',compact('data','alllead','progress','leadstatus'));
        // return $data->all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('lead.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response 
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required|unique:leads',
            'email' => 'required|unique:leads',
            
        ]);
        
        if($request->hasfile('avatar')){ 
            
            $path = $request->file('avatar')->store('images/avatar');
            
            Lead::create([
                'name'=>$request->name,
                'phone'=>$request->phone,
                'email'=>$request->email,
                'remark'=>$request->remark,
                'statusid'=>1,
                'url'=>$path,
                'avatar'=> $request->avatar     
                
            ]);
            return redirect()->route('lead.index')->with('status','Lead with pic add Sucessful!');

        }

        Lead::create([
            'name'=>$request->name,
            'phone'=>$request->phone,
            'email'=>$request->email,
            'remark'=>$request->remark,
            'statusid'=>1,
              
        ]);
        return redirect()->route('lead.index')->with('status','Lead add Sucessful!');

       

    } 

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function show(lead $lead)
    {
        return $lead->load(['leadStatus','cases']);
        return view('lead.show',compact('lead'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function edit(lead $lead)
    {
        $leadstatus= lead_status::all();
        return view('lead.edit',compact('lead','leadstatus')) ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, lead $lead)
    {
        $path = $lead->url;

        if($request->hasfile('avatar')&& $request->file('avatar')->getClientOriginalName()!= $lead->url){ 
            $path = $request->file('avatar')->storeAs('images/avatar',$request->file('avatar')->getClientOriginalName());
        }

        if(!$request->hasfile('avatar')&& !Storage::exists($lead->url)) $path=null;

        $vali=$request->validate([
            'name' => 'required',
            'phone' => 'required|unique:leads,phone,' .$lead->id,
            'email' => 'required|unique:leads,email,' .$lead->id,
            'remark'=>'nullable',
            'statusid'=>'numeric',
            'avatar'=>'nullable|mimes:jpg,jpeg,png'
        ]);
        

            $lead->update([
            'name'=>$request->name,
            'phone'=>$request->phone,
            'email'=>$request->email,
            'remark'=>$request->remark,
            'statusid'=>$request->statusid,
            'url'=>$path,
            'avatar'=>isset($vali['avatar'])?$vali['avatar']:''
        ]);
        
        return redirect()->route('lead.index')->with('status','Lead Edit Sucessful!');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function destroy(lead $lead)
    {
        $lead->delete();

        return redirect()->route('lead.index')->with('status',"The leads $lead->id has been deleted.");
        // return $lead;
    }

    public function leadbulkUpdate(Request $request){
        return DB::table('leads')->whereIn('id',$request->id)->update([
            'statusid'=>$request->status
            ]
        );
        // return $request->all();

        
    }
    public function leadbulkDelete(Request $request){
        return DB::table('leads')->whereIn('id',$request->id)->delete();
    }

}

resources/views/lead/case.blade.php
@extends('adminlte::page')

@section('title', 'Cases')

@section('content_header')
    
@stop

@section('content')

<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h2>cases</h2>
      </div>
    </div>
</div>
            
    <table>
        <thead>
                      
        </thead>
        <tbody>
                        
        </tbody>

@stop

resources/views/lead/create.blade.php
@extends('adminlte::page')

@section('title', 'create')

@section('content_header')
    <h1>add lead</h1>
    
@stop

@section('content')

{{-- <div class="embed-responsive embed-responsive-21by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
</div> --}}
<form action="/lead" method="POST" enctype="multipart/form-data" class="shadow p-3 mb-5 bg-white rounded">
    @csrf

    <div class="mb-3">
      <label for="avatar">Profile Picture</label><hr>
      <input type="file" id=avatar name="avatar" class="dropify" data-allowed-file-extensions="png jpg jpeg"/>
      <div class="alert alert-warning text-center" role="alert">
        Only PNG, JPG and JPEG files allowed !
      </div>
      <button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="right" data-content="Only PNG, JPG and JPEG files allowed !">
        Help
        <span class="spinner-grow spinner-grow-sm text-danger" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      
    </div>

    

    <div class="mb-3 ">
      <label for="name" class="form-label">name</label>
      <input type="text" class="form-control @error('name') is-invalid @enderror shadow p-3 mb-5 bg-white rounded" id="name" name="name" placeholder="Please insert your name" value="{{ old('name') }}">
      
    </div>
    <div class="mb-3">
      <label for="phone" class="form-label">phone</label>
      <input type="text" class="form-control @error('phone') is-invalid @enderror shadow p-3 mb-5 bg-white rounded" id="phone" name="phone" placeholder="Please isnert your phone" value="{{ old('phone') }}">
    </div>

    <div class="mb-3">
        <label for="email" class="form-label">email address</label>
        <input type="email" class="form-control @error('email') is-invalid @enderror shadow p-3 mb-5 bg-white rounded" id="email" name="email" placeholder="Please insert your email" value="{{ old('email') }}">
        
    </div>

    <div class="mb-3">
        <label for="remark" class="form-label">Remark</label>
        <textarea type="remark" class="form-control shadow p-3 mb-5 bg-white rounded" id="remark" name="remark" rows="5">{{ old('remark') }}</textarea>
        
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

@endsection

@section('js')
  <script>
    $('.dropify').dropify().on('dropify.error.imageFormat', function(event, element){
        alert('Image format error message!');
    });

    $(function () {
      $('[data-toggle="popover"]').popover()
    })

    
  </script>
    
@endsection

resources/views/lead/edit.blade.php
@extends('adminlte::page')

@section('title', 'edit')

@section('content_header')
    <h1>edit lead</h1>
@stop

@section('content')


<form action="/lead/{{ $lead->id }}" method="POST" enctype="multipart/form-data">
    @method('PUT')
    @csrf
     {{-- @if ($lead->url)
        <img src="/{{ $lead->url }}" class="rounded d-block" width="80" height="80">';
     @endif --}}
     <div class="mb-3">
        <label for="avatar">Profile Picture</label><hr>
        <input type="file" id=avatar name="avatar" class="dropify" data-allowed-file-extensions="png jpg jpeg" data-default-file="{{ $lead->url ? "/{$lead->url}" : 'https://www.google.com/search?q=profile+picture&rlz=1C1CHBF_enMY878MY878&sxsrf=ALeKk02wt1TCtbeAQFRh4oIBhekHHyGgcg:1624239951479&tbm=isch&source=iu&ictx=1&fir=ZbfgeaptF8Y5ZM%252CSmb2EEjVhvpzWM%252C_&vet=1&usg=AI4_-kTJU2_dnIUFXQeAai0bm1fPuz_Urg&sa=X&ved=2ahUKEwixytmqzafxAhUy4jgGHZGMCsIQ9QF6BAgWEAE#imgrc=ZbfgeaptF8Y5ZM' }}"/>
        <div class="alert alert-warning" role="alert">
          Only PNG, JPG and JPEG files allowed !
        </div>
        <button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="right" data-content="Only PNG, JPG and JPEG files allowed !">
          Help
        </button>
      </div>
    
    <div class="mb-3">
      <label for="name" class="form-label">name</label>
      <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Please insert your name" value="{{ old('name') ? old('name') : $lead->name }}">
      
    </div>
    <div class="mb-3">
      <label for="phone" class="form-label">phone</label>
      <input type="text" class="form-control @error('phone') is-invalid @enderror" id="phone" name="phone" placeholder="Please isnert your phone" value="{{ old('phone') ? old('phone') : $lead->phone }}">
    </div>

    <div class="mb-3">
        <label for="email" class="form-label">email address</label>
        <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="Please insert your email" value="{{ old('email') ? old('email') : $lead->email }}">
        
    </div>

    <div class="mb-3">
        <label for="remark" class="form-label">Remark</label>
        <textarea type="remark" class="form-control" id="remark" name="remark" rows="5">{{ old('remark') ? old('remark') : $lead->remark }}</textarea>
        
    </div>
    <div>
        <select class="form-select form-control" name="statusid" aria-label="Default select example">
            @foreach ($leadstatus as $status)
                <option value="{{ $status->id }}">{{ $status->name }}</option>
            @endforeach
            
        </select>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

@endsection

@section('js')
  <script>
    var $dropify = $('.dropify').dropify();
    $dropify.on('dropify.error.imageFormat', function(event, element){
        alert('Image format error message!');
    });

    $dropify.on('dropify.afterClear', function(event, element){
        alert('File deleted');
    });
    
    $(function () {
      $('[data-toggle="popover"]').popover()
    })
  </script>
    
@endsection

resources/views/lead/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    
@stop

@section('content')
<div class="container ">
	<div class="row">
		<div>
			<x-adminlte-info-box title="Total lead" text="{{ $data->total() }}" icon="fas fa-tasks"
			theme="info"
			progress="{{ $progress }}"
			progresstheme="dark"
			description="{{ $data->total()}}/{{ $alllead }}"
			draggable="true"
			/>
		</div>
		<div class="col-md-12">
			<div class="card mb-3 ">
				<div class="card-header mt-2">
					<div class="col-2"><h3>Leads<span class="badge badge-secondary ml-2">Info</h3></div>
				</div>
				<div class="card-body table-responsive">
	
					<div class="row">
						<div class="col-12">
							<div class="table-responsive">
								<div id="toolbar">
									<div class="form-inline" role="form">
										 <div class="form-group">
											<a href="/lead/create" type="button" class="btnbtn btn-success btn-lg ">Add lead</a> 								 
											<div class="btn-group mr-2"> 
												@foreach ($leadstatus as $status)
													<button id="show" class="btn btn-outline-primary" onclick="leadbulkUpdate({{ $status->id }})">{{$status->name}}</button>
												@endforeach
												<button  class="btn btn-danger" onclick="leadbulkDelete()">Multi Delete</button>
											</div>
										  </div>
									</div>
								</div>
								<table 
										class="table table-striped table-bordered "
										id="leadtable"
										data-toggle="table" 
										data-search="true"
										{{-- data-url="/api/getItemById/{{ $case->id }}" --}}
										{{-- data-side-pagination="server" --}}
										data-pagination="true"
										data-server-sort="false"
										data-show-export="true"
										data-export-data-type="all"
										data-query-params="queryParams"
										{{-- data-sticky-header="true" --}}
										data-height="600"
										data-toolbar="#toolbar"
										data-click-to-select="true"
										data-show-print="true"
										data-use-pipeline="true"
										data-pipeline-size="500"
										data-show-columns="true"
										data-show-columns-search="true"
										data-show-columns-toggle-all="true"
										data-smart-display="true"
										data-thead-classes="thead-light"
										data-filter-control="true"
										data-show-search-clear-button="true"
										data-server-sort="false"

									>
								
									<thead>
										<th data-checkbox="true"></th>
										<th data-sortable="true" data-field="url" data-formatter="AvatarFormatter">Image</th>
										<th data-sortable="true" data-field="id">Lead id</th>
										<th data-sortable="true" data-field="name" data-filter-control="input">Name</th>
										<th data-sortable="true" data-field="phone" data-filter-control="input">Phone</th>
										<th data-sortable="true" data-field="email" data-filter-control="input">Email</th>
										<th data-sortable="true" data-field="remark">Remark</th>
										<th data-sortable="true" data-field="cases">Cases</th>
										<th data-sortable="true" data-field="status" data-filter-control="input">Status</th>
										<th data-sortable="true" data-field="created_at">Created at</th>
										<th data-sortable="true" data-field="updated_at">Updated at</th>
										<th>Edit</th>
										<th>Delete</th>
									</thead>
									
									<tbody>
										@foreach ($data as $lead)
										<tr> 
										<td></td>
										<td>{{ $lead->url}}</td>
										<td>{{ $lead->id}}</td>
										<td>{{ $lead->name}}</td>
										<td>{{ $lead->phone}}</td>
										<td>{{ $lead->email}}</td>
										<td>{{ $lead->remark}}</td>
										<td>
											
											<button onclick="showcase()">
											{{ $lead->cases_count }}
											</button>
											
										</td>
										<td>{{ $lead->leadStatus->name}}</td>
										<td>{{ $lead->created_at}}</td>
										<td>{{ $lead->updated_at}}</td>
										<td><a href="/lead/{{ $lead->id }}/edit " type="button" class="btn btn-warning" >edit</a></td>
										<td>
										<form action="/lead/{{ $lead->id }}" method="POST">
											@method('DELETE')
											@csrf
											<button type="submit" class="btn btn-danger">delete</button>
										</form>
										</td>
										
										
										</tr>
									@endforeach
									</tbody>
									
								</table>
							</div>
						</div>
					</div>
					<br>
					<div class="float-right">
						{{ $data->links() }}
					</div>
				</div>
			</div>
		</div>
	</div>	
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> 

    var $table = $('#leadtable')

	function leadbulkUpdate(status){
        
		var id=[];
		$table.bootstrapTable('getSelections').map((value,index)=>{
			id.push(value.id);
		})

		$.post("/api/leadbulkUpdate",{id:id,status:status},function(data,status){
			// alert("DATA:"+data+"\nStatus:"+status);
			location.reload();
		});
		
	  
	  }

  function leadbulkDelete(){
	  
		var id=[];
		$table.bootstrapTable('getSelections').map((value,index)=>{
			id.push(value.id);
		})

		$.post("/api/leadbulkDelete",{id:id},function(data,status){
			location.reload();
		});
	  
	  }

	  function AvatarFormatter(value){
			return value && '<img src="'+value+'" class="rounded mx-auto d-block" width="80" height="auto">';
	  }

	
	</script>
	
@stop