routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\CasemangeController;
use App\Http\Controllers\CaseitemController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
// Route::get('/', function () { return view('home');});
Route::resource('/', HomeController::class);
Route::resource('/lead', LeadController::class);
Route::resource('/cases', CasemangeController::class);
Route::resource('/item', CaseitemController::class);
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/casemange.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class casemange extends Model
{
    use HasFactory;
    protected $guarded = [];
    public function caseStatus()
    {
        return $this->belongsTo(casestatus::class, 'casestatus');
    }

    public function lead()
    {
        return $this->belongsTo(lead::class,'lead_id','id');
    }

    public function items()
	{
		return $this->hasMany(caseitem::class,'case_id');
	}

}

app/Http/Controllers/CasemangeController.php
<?php

namespace App\Http\Controllers;

use App\Models\lead;
use App\Models\caseitem;
use App\Models\casemange;
use App\Models\casestatus;
use Illuminate\Http\Request;
use App\Models\CaseItemStatus;
use Illuminate\Support\Facades\DB;
use Database\Seeders\CasestatusSeeder;

class CasemangeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    //    $casedata = casemange::withCount('items')->with('lead','caseStatus')->get();
       $casestatus = casestatus::all();
       $casedata = casemange::withCount('items')->with('lead','caseStatus')->paginate(10);
       
        return view('casemange.index',compact('casedata','casestatus'));
        // return $casedata;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('casemange.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //  
        $request->validate([
            'name' => 'required',

        ]);
        $max = lead::count('id');

         Casemange::create([
            
            'lead_id'=>rand(1,$max),
            'casestatus'=>rand(1,2),
        ]
            
        );

        return redirect()->route('cases.index')->with('status','Case Create Sucessful!');
    }
        

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\casemange  $casemange
     * @return \Illuminate\Http\Response
     */
    public function show(casemange $case)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\casemange  $casemange
     * @return \Illuminate\Http\Response
     */
    public function edit(casemange $case)
    {
        

        $casestatus= casestatus::all();
        $itemstatus= CaseItemStatus::all();
        $items= caseitem::where('case_id',$case->id)->orderBy('created_at','desc')->paginate(5);
 
        // $items=["total"=>$items->total(),"rows"=>$items];
        // return $items;

        
        // $case->load('items');
        // return $case;
        
        return view('casemange.edit',['case'=>$case,'casestatus'=>$casestatus,'items'=>$items,'itemstatus'=>$itemstatus]) ;

        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\casemange  $casemange
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, casemange $case)
    {
        //
        // return $request->all();
         $case->update([
            
            'casestatus'=>$request->statusid,
        ]);
        return redirect()->route('cases.index')->with('status', "Cases updated successful");

        // return $case;
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\casemange  $casemange
     * @return \Illuminate\Http\Response
     */
    public function destroy(casemange $case)
    {   
        $case->delete();
        
        // return $case;
        
        return redirect()->route('cases.index')->with('status',"The case $case->id has been deleted.");
       
        
    }

    public function getAllItem(casemange $case){
        $casestatus= casestatus::all();
        $itemstatus= CaseItemStatus::all();
        $items= caseitem::where('case_id',$case->id)->orderBy('created_at','desc')->paginate(5);
 
        // return $items=["total"=>$items->total(),"rows"=>$items];
    }

    public function getItemsById($id){
        return caseitem::where('case_id',$id)->orderBy('created_at','desc')->paginate(10);

    }

    public function casebulkUpdate(Request $request){
        return DB::table('casemanges')->whereIn('lead_id',$request->leadid)->update([
            'casestatus'=>$request->status
            ]
        );
        // return $request->all(); 

        
    }
    public function casebulkDelete(Request $request){
        return DB::table('casemanges')->whereIn('lead_id',$request->leadid)->delete();
    }
    
    public function caseChartData(){
        $select= DB::select("SELECT count(id) AS total,casestatus,substring(updated_at,1,7)AS 'month' FROM casemanges GROUP BY substring(updated_at,1,7),casestatus ORDER BY substring(updated_at,1,7);");
        $formattedData=[];
        $doing=[];
        $done=[];
        foreach ($select as $data) {
            # code...
            $month = date('M',strtotime($data->month));
            $formattedData[$month]['month']=$month;
            if ($data->casestatus == 1) {
                $label="doing";
                $doing[]=$data->total;
            }else{
                $label="done";
                $done[]=$data->total;
            }
            $formattedData[$month][$label]=$data->total;
        } 

        // return $formattedData;
        $keys=array_keys($formattedData);
        $data=array_values($formattedData);

        return ["labels"=>$keys,"data"=>$formattedData,"doing"=>$doing,"done"=>$done];
    }
    
}
 

resources/views/casemange/create.blade.php
@extends('adminlte::page')

@section('title', 'createcase')

@section('content_header')
    <h1>add case</h1>
@stop

@section('content')



<form action="/cases" method="POST">
  @csrf
    <div class="mb-3">
    <label for="name" class="form-label">Lead name</label>
    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Please insert your name" value="{{ old('name') }}">
    <br>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection

resources/views/casemange/edit.blade.php
@extends('adminlte::page')

@section('title', 'editcase')

@section('content_header')
    <h1>edit case | {{$case->id }}</h1>
@stop

@section('content')



<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <form action="/cases/{{ $case->id }}" method="POST">
        @method('PUT')
        @csrf
        <div class="mb-3">
            <label for="name" class="form-label">Lead id</label>
            <input type="text" class="form-control" id="lead_id" name="lead_id"  value="{{ old('lead_id') ? old('lead_id') : $case->lead_id }}" readonly="true">
        </div>

        <div class="mb-3">
          <label for="name" class="form-label">Lead Name</label>
          <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name"  value="{{ old('name') ? old('name') : $case->lead->name }}" readonly='true'>
        </div>
        <div>
            <label for="casestatus" class="form-label">Case Status</label>
            <select class="form-select form-control" name="statusid" aria-label="Default select example">
                @foreach ($casestatus as $status)
                    <option value="{{ $status->id }}">{{ $status->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div>

    <br>

  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h2>Items<span class="badge badge-secondary ml-2">Info</h2>
        <div id="toolbar">
          <div class="form-inline" role="form">
            <div class="form-group">
              <a href="/item/create?case_id={{ $case->id }}" class="btn btn-primary">Add</a>
                
              <div class="btn-group mr-2"> 
                  @foreach ($itemstatus as $status)
                      <button id="show" class="btn btn-outline-primary" onclick="bulkUpdate({{$status->id}})">{{$status->name}}</button>
                  @endforeach
                  <button  class="btn btn-danger" onclick="bulkDelete()">Multi Delete</button>
              </div>
            </div>
          </div>
        </div>
            
              <table class="table table-border table-striped" 
                    id="table"
                    data-toggle="table" 
                    data-search="true"
                    {{-- data-url="/api/getAllItem/{{ $case->id }}"
                    data-side-pagination="server"  --}}
                    
                    data-pagination="true"
                    data-server-sort="false"
                    data-show-export="true"
                    data-export-data-type="all"
                    data-query-params="queryParams"
                    data-sticky-header="true"
                    data-toolbar="#toolbar"
                    data-click-to-select="true"
                    >
                  <thead>
                      <tr>
                        <th data-checkbox="true"></th>
                        <th data-sortable="true" data-field="id">ID</th>
                        <th data-sortable="true" data-field="task">Task</th>
                        <th data-sortable="true" data-field="orderdate">Order Date</th>
                        <th data-sortable="true" data-field="executedate">Execute Date</th> 
                        <th data-sortable="true" data-field="status">Status</th>
                        <th data-sortable="true" data-field="created_at">Created At</th>
                        <th data-sortable="true" data-field="updated_at">Updated At</th>
                        <th>edit</th>
                        <th>delete</th>
                      </tr>
                  </thead>
                  <tbody>
                        @foreach($items as $item)
                            <tr>
                                <td></td>
                                <td>{{$item->id}}</td>
                                <td>{{$item->task}}</td>
                                <td>{{$item->orderdate}}</td>
                                <td>{{$item->executedate}}</td>
                                <td>{{$item->status->name}}</td>
                                <td>{{$item->created_at}}</td>
                                <td>{{$item->updated_at}}</td>
                                <td><a href="/item/{{$item->id}}/edit" type="button" class="btn btn-warning">edit</a></td>
                                
                                <td>
                                   <form action="/item/{{ $item->id }}" method="POST">
                                      @method('DELETE')
                                      @csrf
                                       <button type="submit" class="btn btn-danger">Delete</button>
                                    </form> 
                                    {{-- <button type="submit" class="btn btn-danger" onclick="mydelete('{{ $item->id }}')">Delete</button> --}}
                                </td>
                            </tr>
                        @endforeach
                  </tbody>

              </table>
              <div class="float-right">
                {{$items->links()}}
              </div>
        </div>
      </div>
    </div>

@stop

@section('js')
<script>
    var $table = $('#table')

    function bulkUpdate(status){
        
          var id=[];
          $table.bootstrapTable('getSelections').map((value,index)=>{
              id.push(value.id);
          })

          $.post("/api/bulkUpdate",{id:id,status:status},function(data,status){
            // console.log(data);
            // alert("DATA:"+data+"\nStatus:"+status);
              location.reload();
          });
          
        
        }

    function bulkDelete(){
        
          var  id=[];
          $table.bootstrapTable('getSelections').map((value,index)=>{
              id.push(value.id);
          })

          $.post("/api/bulkDelete",{id:id},function(data,status){
              // alert("Delete:"+data+"\nStatus:"+status);
              location.reload();
          });
        
        }
      // function mydelete(id){

      //   var success = "";
      //   var post = $.ajax({
      //       type: "DELETE",
      //       url: "/item/"+id,
           
      //       success: function(res){
      //         console.log(res);
      //         if(res){
      //           alert("deleted") 
      //           location.reload();
      //         }
      //       },
            
      //     })
      // }
  </script>
    
@stop

resources/views/casemange/index.blade.php
@extends('adminlte::page')

@section('title', 'casemanage')

@section('content_header')
    
@stop

@section('content')
<div class="container">
	<div class="col-md-12">
		<div class="card" style="height: 80vh">
			<div class="card-header row">
				<div class="col-3"><h1>Case<span class="badge badge-secondary ml-1">Info</h1></div>	
			</div>
			<div class="card-body table-responsive">
				<div id="toolbar">
					<div class="form-inline" role="form">
						<div class="form-group">
							<a href="/cases/create" type="button" class="btnbtn btn-success btn-lg">Add case</a> 
							<div class="btn-group mr-2"> 
								@foreach ($casestatus as $status)
									<button id="show" class="btn btn-outline-primary" onclick="casebulkUpdate({{$status->id}})">{{$status->name}}</button>
								@endforeach
								<button  class="btn btn-danger" onclick="casebulkDelete()">Multi Delete</button>
							</div>
						</div>
					</div>
				</div>

					<table 
					
							class="table table-striped table-bordered "
							id="casetable"
							data-toggle="table" 
							data-search="true"
							{{-- data-url="/api/getItemById/{{ $case->id }}" --}}
							{{-- data-side-pagination="server" --}}
							data-pagination="true"
							data-server-sort="false"
							data-show-export="true"
							data-export-data-type="all"
							data-query-params="queryParams"
							{{-- data-sticky-header="true"
							data-sticky-header-offset-y="120" --}}
							data-toolbar="#toolbar"
							data-click-to-select="true">

						<thead>
							<th data-checkbox="true"></th>
							<th data-sortable="true" data-field="lead_id">Lead Id</th>
							<th data-sortable="true" data-field="lead_name">Lead Name</th>
							<th data-sortable="true" data-field="item">Item</th>
                            <th data-sortable="true" data-field="casestatus">casestatus</th>
							<th data-sortable="true" data-field="created_at">Created at</th>
							<th data-sortable="true" data-field="updated_at">Updated at</th>
							<th>Edit</th>
							<th>Delete</th>
						</thead>
                        
                        <tbody>
							@foreach ($casedata as $item)
							<tr>
							<td></td>
							<td>{{ $item->lead_id }}</td>
							<td>
								@if ($item->lead)
									{{ $item->lead->name}}
								@else
								@endif	
							</td>
							<td>{{ $item->items_count }}</td>
							<td>{{ $item->caseStatus->name}}</td>
							<td>{{ $item->created_at}}</td>
                            <td>{{ $item->updated_at }}</td>
							<td><a href="/cases/{{ $item->id}}/edit " type="button" class="btn btn-warning" >edit</a></td>
							<td>
							<form action="/cases/{{ $item->id}}" method="POST">
								@method('DELETE')
								@csrf
								<button type="submit" class="btn btn-danger">delete</button>
							</form>
							</td>
						</tr>
							@endforeach
                        </tbody>
						
					</table>

			</div>
		</div>
		<div class="float-right">
			{{$casedata->links()}}
		</div>
	</div>
		<br>
		<br>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> 
		var $table = $('#casetable')
		function casebulkUpdate(status){
			// console.log(status);
			var leadid=[];
			$table.bootstrapTable('getSelections').map((value,index)=>{
				// console.log(value);
				leadid.push(value.lead_id);
				// console.log(id);
		})
			

			$.post("/api/casebulkUpdate",{leadid:leadid,status:status},function(data,status){
				// console.log(data);
				// alert("DATA:"+data+"\nStatus:"+status);
				location.reload();
				$table.bootstrapTable(refresh);
			});
				
	  
	  }

 		 function casebulkDelete(){
	  
			var leadid=[];
			$table.bootstrapTable('getSelections').map((value,index)=>{
				leadid.push(value.lead_id);
			})

		$.post("/api/casebulkDelete",{leadid:leadid},function(data,status){
			location.reload();
		});
	  
	  }
	
	</script>
@stop